openapi: 3.0.3

info:
  title: Bu Groups API
  version: 1.0.0

paths:
  /rest/groups:
    get:
      tags:
        - groups
      operationId: getAllGroups
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: 'groups-dtos.yaml#/components/schemas/GroupDTO'
    post:
      tags:
        - groups
      operationId: postGroup
      requestBody:
        content:
          application/json:
            schema:
              $ref: 'groups-dtos.yaml#/components/schemas/GroupDTO'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'groups-dtos.yaml#/components/schemas/GroupDTO'
  /rest/groups/{groupId}:
    delete:
      tags:
        - groups
      operationId: deleteGroup
      parameters:
        - name: groupId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: 'groups-dtos.yaml#/components/schemas/GroupDTO'
