openapi: 3.0.3

info:
  title: BU Subjects DTOs
  version: 1.0.0
paths: {}

components:
  schemas:
    SubjectDTO:
      title: SubjectDTO
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type: string
        teacherId:
          type: string
          format: uuid
        groupId:
          type: string
          format: uuid
