openapi: 3.0.3

info:
  title: BU Teachers DTOs
  version: 1.0.0
paths: {}

components:
  schemas:
    TeacherDTO:
      title: TeacherDTO
      type: object
      properties:
        id:
          type: string
          format: uuid
        lastName:
          type: string
        firstName:
          type: string
        patronymic:
          type: string
