services:

  mongo:
    image: "mongo:6.0.7"
    container_name: "dev-mongodb"
    volumes:
      - my-db:/data/db
      - ./docker/mongo-init/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
      MONGO_INITDB_DATABASE: bu-journal
      BU_JOURNAL_MONGO_DB_DATABASE: bu-journal
      BU_JOURNAL_MONGO_DB_USERNAME: bu-journal
      BU_JOURNAL_MONGO_DB_PASSWORD: password

volumes:
  my-db:
    driver: local
