# Use postgres/example user/password credentials
version: '3.1'

services:

  mongo:
    image: "mongo:6.0.7"
    container_name: "dev-mongodb"
    volumes:
      - my-db:/var/lib/mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
  my-db:
    driver: local